version: '3.7'

services:

  # Database
  db:
    image: postgres:12.1-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: always
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
      - ../sql/:/docker-entrypoint-initdb.d/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s

  # Nginx
  nginx:
    build:
      context: nginx
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    command: /bin/bash -c "envsubst '$$NGINX_PORT $$NGINX_ROOT $$NGINX_HOST $$PHP_HOST $$PHP_PORT' < /etc/nginx/site.conf.tmpl > /etc/nginx/sites-available/site.conf && nginx -g 'daemon off;'"
    restart: always
    expose:
      - ${APP_PORT}
    working_dir: /etc/nginx
    depends_on:
      - php
    links:
      - php:${PHP_HOST}
    environment:
      - VIRTUAL_HOST=${APP_HOST}
      - VIRTUAL_PORT=${APP_PORT}
      - VIRTUAL_PROTO=${APP_PROTOCOL}
      - VIRTUAL_NETWORK=proxy
      - NGINX_ROOT=${APP_PATH}
      - NGINX_HOST=${APP_HOST}
      - NGINX_PORT=${APP_PORT}
      - PHP_HOST=${PHP_HOST}
      - PHP_PORT=${PHP_PORT}
    volumes:
      - ${SOURCE_PATH}:${APP_PATH}
      - ../log/nginx/:/var/log/nginx
      - ../etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../etc/nginx/site.conf.tmpl:/etc/nginx/site.conf.tmpl
      - ../certs:/etc/nginx/certs:rw
      - /etc/nginx/sites-available
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - proxy
      - default
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 5s

  # PHP
  php:
    build:
      context: php-fpm
      target: php
      args:
        - UID=${UID}
        - GID=${GID}
        - INSTALL_OPCACHE=${PHP_INSTALL_OPCACHE}
        - INSTALL_XDEBUG=${PHP_INSTALL_XDEBUG}
    container_name: ${COMPOSE_PROJECT_NAME}-php
    restart: always
    expose:
      - ${PHP_PORT}
    user: ${UID}:${GID}
    working_dir: ${APP_PATH}
    environment:
      - UID=${UID}
      - GID=${GID}
      - XDEBUG_MODE=${PHP_XDEBUG_MODE:-off}
    volumes:
      - ${SOURCE_PATH}:${APP_PATH}
    depends_on:
      - db
    links:
      - db:${DB_HOST}
    healthcheck:
      test: healthcheck || echo 1
      interval: 5s

volumes:
  db:

networks:
  proxy:
    name: proxy
    external: true